/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package DataMusik;

/**
 *
 * @author HP
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.persistence.*;

public class InsertDlgAlbum extends javax.swing.JDialog {

    private Utama utama;
    private DefaultTableModel model; // simpan model dari parent
    private boolean saved = false;

    /**
     * Creates new form InsertDlgAlbum
     */
    public InsertDlgAlbum(java.awt.Frame parent, boolean modal, Utama utama) {
        super(parent, modal);
        initComponents();
        this.utama = utama; // simpan referensi agar tidak null
    }

    public InsertDlgAlbum(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null);
    }

    public boolean isSaved() {
        return saved;
    }

    // Ambil data album dari textfield
    public String[] getDataAlbum() {

        return new String[]{
            tfID.getText(), // ID
            tfNama.getText(), // Nama
            tfGenre.getText(), // Genre
            tfTahun.getText() // Tahun
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlInputkanData = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        jlNama = new javax.swing.JLabel();
        jlGenre = new javax.swing.JLabel();
        jlTahun = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfGenre = new javax.swing.JTextField();
        tfTahun = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 191, 220));

        jlInputkanData.setFont(new java.awt.Font("Baloo", 0, 24)); // NOI18N
        jlInputkanData.setText("INPUTKAN DATA ALBUM");

        jlID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlID.setText("ID Album");

        jlNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlNama.setText("Nama Album");

        jlGenre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlGenre.setText("Genre");

        jlTahun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlTahun.setText("Tahun Rilis");

        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(173, 216, 240));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 153, 153));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlInputkanData)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlID, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jlTahun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTahun)
                            .addComponent(tfNama)
                            .addComponent(tfGenre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(34, 34, 34))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClear, btnSave});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlInputkanData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlID)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGenre)
                    .addComponent(tfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTahun))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClear, btnSave});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (tfID.getText().equals("") || tfNama.getText().equals("")
                || tfGenre.getText().equals("") || tfTahun.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Isi semua data terlebih dahulu!");
        } else {
            String id, nama, genre;
            id = tfID.getText();
            nama = tfNama.getText();
            genre = tfGenre.getText();
            int tahun;

            try {
                tahun = Integer.parseInt(tfTahun.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Tahun harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Buat koneksi persistence
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBOPertemuanDuabelasPU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();

            // 🔎 Cek apakah ID sudah ada di database
            Album existing = em.find(Album.class, id);
            if (existing != null) {
                JOptionPane.showMessageDialog(null, "ID Album sudah ada! Gunakan ID lain.", "Duplikasi ID", JOptionPane.ERROR_MESSAGE);
                em.close();
                emf.close();
                return; // stop proses
            }

            // Cek apakah judul film sudah ada
            Query q = em.createQuery("SELECT COUNT(a) FROM Album a WHERE a.namaAlbum = :namaAlbum");
            q.setParameter("namaAlbum", nama);
            long count = (long) q.getSingleResult();

            if (count > 0) {
                JOptionPane.showMessageDialog(null, "Nama album sudah ada!", "Error", JOptionPane.ERROR_MESSAGE);
                em.getTransaction().rollback();
                return;
            }
            

            // Buat object Album
            Album a = new Album();
            a.setIdAlbum(id);
            a.setNamaAlbum(nama);
            a.setGenre(genre);
            a.setTahunRilis(tahun);

            // Simpan ke database
            em.persist(a);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(null, "Data Album berhasil disimpan!");

            // Bersihkan field input
            bersih();

            // Refresh tabel di JFrame (pastikan ada method showTable() di JFrame)
            utama.showTableAlbum();

            em.close();
            emf.close();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        bersih();
    }//GEN-LAST:event_btnClearActionPerformed

    private void bersih() {
        tfID.setText("");
        tfNama.setText("");
        tfGenre.setText("");
        tfTahun.setText("");
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InsertDlgAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                InsertDlgAlbum dialog = new InsertDlgAlbum(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlGenre;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlInputkanData;
    private javax.swing.JLabel jlNama;
    private javax.swing.JLabel jlTahun;
    private javax.swing.JTextField tfGenre;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTahun;
    // End of variables declaration//GEN-END:variables
}
