/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DataMusik;

/**
 *
 * @author HP
 */
import java.io.File;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import javax.persistence.*;

public class Utama extends javax.swing.JFrame {

    private DefaultTableModel model;
    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/PBOPertemuanDuabelas";
    String user = "postgres";
    String password = "01234567";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);

    /**
     * Creates new form DataMusik
     */
    public Utama() {
        initComponents();
        showTableAlbum();
        showTableMusik();
    }

    public void showTableAlbum() {
        EntityManager em = Persistence.createEntityManagerFactory("PBOPertemuanDuabelasPU").createEntityManager();
        Query q = em.createNamedQuery("Album.findAll");
        List<Album> hasil = q.getResultList();

        DefaultTableModel modelAlbum = new DefaultTableModel(new String[]{"ID Album", "Nama Album", "Genre", "Tahun Rilis"}, 0);
        for (Album a : hasil) {
            modelAlbum.addRow(new Object[]{a.getIdAlbum(), a.getNamaAlbum(), a.getGenre(), a.getTahunRilis()});
        }
        jTblAlbum.setModel(modelAlbum);
    }

    public void showTableMusik() {
        EntityManager em = Persistence.createEntityManagerFactory("PBOPertemuanDuabelasPU").createEntityManager();
        Query q = em.createNamedQuery("Musik.findAll");
        List<Musik> hasil = q.getResultList();

        DefaultTableModel modelMusik = new DefaultTableModel(
                new String[]{"ID Lagu", "Nama Album", "Judul", "Artis"}, 0);

        for (Musik m : hasil) {

            // ambil data dari relasi Album (FK)
            String idAlbum = (m.getIdAlbum() != null) ? m.getIdAlbum().getNamaAlbum() : "";

            modelMusik.addRow(new Object[]{
                m.getIdMusik(),
                m.getIdAlbum().getNamaAlbum(),
                m.getJudul(), // kolom ke-3 = Judul
                m.getArtis(), // kolom ke-4 = Artis
            });
        }

        jTblMusik.setModel(modelMusik);
        em.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlJudulForm = new javax.swing.JLabel();
        jTPAlbum = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblAlbum = new javax.swing.JTable();
        btnInsertAlbum = new javax.swing.JButton();
        btnUpdateAlbum = new javax.swing.JButton();
        btnDeleteAlbum = new javax.swing.JButton();
        btnUploadAlbum = new javax.swing.JButton();
        btnCetakAlbum = new javax.swing.JButton();
        btnDownloadAlbum = new javax.swing.JButton();
        btnResetAlbum = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblMusik = new javax.swing.JTable();
        btnInsertMusik = new javax.swing.JButton();
        btnUpdateMusik = new javax.swing.JButton();
        btnDeleteMusik = new javax.swing.JButton();
        btnUploadMusik = new javax.swing.JButton();
        btnCetakMusik = new javax.swing.JButton();
        btnDownloadMusik = new javax.swing.JButton();
        btnResetMusik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 191, 220));

        jlJudulForm.setFont(new java.awt.Font("Baloo", 1, 36)); // NOI18N
        jlJudulForm.setText("KOLEKSI MUSIK");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 204));

        jTblAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Album", "Nama Album", "Genre", "Tahun Rilis"
            }
        ));
        jScrollPane3.setViewportView(jTblAlbum);

        btnInsertAlbum.setBackground(new java.awt.Color(173, 216, 240));
        btnInsertAlbum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsertAlbum.setText("Insert");
        btnInsertAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertAlbumActionPerformed(evt);
            }
        });

        btnUpdateAlbum.setBackground(new java.awt.Color(152, 251, 152));
        btnUpdateAlbum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateAlbum.setText("Update");
        btnUpdateAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAlbumActionPerformed(evt);
            }
        });

        btnDeleteAlbum.setBackground(new java.awt.Color(255, 102, 105));
        btnDeleteAlbum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteAlbum.setText("Delete");
        btnDeleteAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAlbumActionPerformed(evt);
            }
        });

        btnUploadAlbum.setBackground(new java.awt.Color(153, 204, 255));
        btnUploadAlbum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUploadAlbum.setText("Upload");
        btnUploadAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadAlbumActionPerformed(evt);
            }
        });

        btnCetakAlbum.setBackground(new java.awt.Color(255, 255, 153));
        btnCetakAlbum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCetakAlbum.setText("Cetak");
        btnCetakAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakAlbumActionPerformed(evt);
            }
        });

        btnDownloadAlbum.setBackground(new java.awt.Color(255, 153, 255));
        btnDownloadAlbum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDownloadAlbum.setText("Download");
        btnDownloadAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadAlbumActionPerformed(evt);
            }
        });

        btnResetAlbum.setBackground(new java.awt.Color(255, 204, 0));
        btnResetAlbum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetAlbum.setText("Reset");
        btnResetAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetAlbumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInsertAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnResetAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUploadAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDownloadAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCetakAlbum)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteAlbum, btnUpdateAlbum});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnResetAlbum, btnUploadAlbum});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAlbum)
                    .addComponent(btnUploadAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetakAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDownloadAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetAlbum))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDeleteAlbum, btnInsertAlbum, btnUpdateAlbum});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnResetAlbum, btnUploadAlbum});

        jTPAlbum.addTab("Album", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jTblMusik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Lagu", "Nama Album", "Judul", "Artis"
            }
        ));
        jScrollPane1.setViewportView(jTblMusik);

        btnInsertMusik.setBackground(new java.awt.Color(173, 216, 240));
        btnInsertMusik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsertMusik.setText("Insert");
        btnInsertMusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertMusikActionPerformed(evt);
            }
        });

        btnUpdateMusik.setBackground(new java.awt.Color(152, 251, 152));
        btnUpdateMusik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateMusik.setText("Update");
        btnUpdateMusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMusikActionPerformed(evt);
            }
        });

        btnDeleteMusik.setBackground(new java.awt.Color(255, 102, 105));
        btnDeleteMusik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteMusik.setText("Delete");
        btnDeleteMusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMusikActionPerformed(evt);
            }
        });

        btnUploadMusik.setBackground(new java.awt.Color(153, 204, 255));
        btnUploadMusik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUploadMusik.setText("Upload");
        btnUploadMusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadMusikActionPerformed(evt);
            }
        });

        btnCetakMusik.setBackground(new java.awt.Color(255, 255, 153));
        btnCetakMusik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCetakMusik.setText("Cetak");
        btnCetakMusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakMusikActionPerformed(evt);
            }
        });

        btnDownloadMusik.setBackground(new java.awt.Color(255, 153, 255));
        btnDownloadMusik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDownloadMusik.setText("Download");
        btnDownloadMusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadMusikActionPerformed(evt);
            }
        });

        btnResetMusik.setBackground(new java.awt.Color(255, 204, 0));
        btnResetMusik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetMusik.setText("Reset");
        btnResetMusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetMusikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnInsertMusik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateMusik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteMusik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnResetMusik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUploadMusik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDownloadMusik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCetakMusik)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertMusik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateMusik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteMusik)
                    .addComponent(btnUploadMusik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetakMusik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDownloadMusik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetMusik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDeleteMusik, btnUploadMusik});

        jTPAlbum.addTab("Musik", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlJudulForm)
                .addGap(209, 209, 209))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTPAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jlJudulForm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTPAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertAlbumActionPerformed
        InsertDlgAlbum dialog = new InsertDlgAlbum(this, true, this); // tambahkan 'this' untuk kirim referensi album
        dialog.setVisible(true);
    }//GEN-LAST:event_btnInsertAlbumActionPerformed

    private void btnInsertMusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertMusikActionPerformed
        InsertDlgMusik dialog = new InsertDlgMusik(this, true, this); // tambahkan 'this' untuk kirim referensi album
        dialog.setVisible(true);
    }//GEN-LAST:event_btnInsertMusikActionPerformed

    private void btnUpdateAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAlbumActionPerformed
        int row = jTblAlbum.getSelectedRow();
        if (row != -1) {
            // ambil data dari tabel
            String id = jTblAlbum.getValueAt(row, 0).toString();
            String nama = jTblAlbum.getValueAt(row, 1).toString();
            String genre = jTblAlbum.getValueAt(row, 2).toString();
            String tahun = jTblAlbum.getValueAt(row, 3).toString();

            // buka dialog update
            UpdateDlgAlbum dialog = new UpdateDlgAlbum(this, true, this, id, nama, genre, tahun);
            dialog.setVisible(true);

            // reload tabel setelah update
            if (dialog.isUpdated()) {
                showTableAlbum();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau diupdate dulu!");
        }
    }//GEN-LAST:event_btnUpdateAlbumActionPerformed

    private void btnDeleteMusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMusikActionPerformed
        int row = jTblMusik.getSelectedRow();
        if (row >= 0) {
            // Ambil data dari tabel
            String idLagu = jTblMusik.getValueAt(row, 0).toString();
            String idAlbum = jTblMusik.getValueAt(row, 1).toString();
            String judul = jTblMusik.getValueAt(row, 2).toString();
            String artis = jTblMusik.getValueAt(row, 3).toString();

            // Panggil dialog, kirim form ini sebagai parent
            DeleteDlgMusik dialog = new DeleteDlgMusik(this, true, this, idLagu, idAlbum, judul, artis);
            dialog.setVisible(true);

            // Kalau user benar-benar delete, refresh tabel
            if (dialog.isDeleted()) {
                showTableMusik();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data dulu dari tabel!");
        }
    }//GEN-LAST:event_btnDeleteMusikActionPerformed

    private void btnDeleteAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAlbumActionPerformed
        int row = jTblAlbum.getSelectedRow();
        if (row >= 0) {
            // Ambil data dari tabel
            String id = jTblAlbum.getValueAt(row, 0).toString();
            String nama = jTblAlbum.getValueAt(row, 1).toString();
            String genre = jTblAlbum.getValueAt(row, 2).toString();
            String tahun = jTblAlbum.getValueAt(row, 3).toString();

            // Panggil dialog, kirim form ini sebagai parent
            DeleteDlgAlbum dialog = new DeleteDlgAlbum(this, true, this, id, nama, genre, tahun);
            dialog.setVisible(true);

            // Kalau user benar-benar delete, refresh tabel
            if (dialog.isDeleted()) {
                showTableMusik();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data dulu dari tabel!");
        }
    }//GEN-LAST:event_btnDeleteAlbumActionPerformed

    private void btnUpdateMusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMusikActionPerformed
        int row = jTblMusik.getSelectedRow();
        if (row != -1) {
            // ambil data dari tabel
            String idLagu = jTblMusik.getValueAt(row, 0).toString();
            String idAlbum = jTblMusik.getValueAt(row, 1).toString();
            String judul = jTblMusik.getValueAt(row, 2).toString();
            String artis = jTblMusik.getValueAt(row, 3).toString();

            // buka dialog update
            UpdateDlgMusik dialog = new UpdateDlgMusik(this, true, this, idLagu, idAlbum, judul, artis);
            dialog.setVisible(true);

            // reload tabel setelah update
            if (dialog.isUpdated()) {
                showTableMusik();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau diupdate dulu!");
        }
    }//GEN-LAST:event_btnUpdateMusikActionPerformed

    private void btnUploadAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadAlbumActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File filePilihan = jfc.getSelectedFile();
            System.out.println("yang dipilih : " + filePilihan.getAbsolutePath());

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBOPertemuanDuabelasPU");
            EntityManager em = emf.createEntityManager();

            int jumlahBerhasil = 0;
            int jumlahDuplikat = 0;
            int jumlahGagal = 0;

            try (BufferedReader br = new BufferedReader(new FileReader(filePilihan))) {
                String baris;
                String pemisah = ";";

                em.getTransaction().begin();

                while ((baris = br.readLine()) != null) {
                    String[] data = baris.split(pemisah);

                    // validasi data
                    if (data.length < 4) {
                        jumlahGagal++;
                        continue;
                    }

                    String idAlbum = data[0].trim();
                    String nama = data[1].trim();
                    String genre = data[2].trim();

                    // Cek data kosong
                    if (idAlbum.isEmpty() || nama.isEmpty() || genre.isEmpty()) {
                        jumlahGagal++;
                        continue;
                    }

                    // parse tahun (hanya 1 deklarasi)
                    int tahun;
                    try {
                        tahun = Integer.parseInt(data[3].trim());
                    } catch (NumberFormatException ex) {
                        jumlahGagal++;
                        continue;
                    }

                    // Cek duplikat ID
                    Album cekID = em.find(Album.class, idAlbum);
                    if (cekID != null) {
                        jumlahDuplikat++;
                        continue;
                    }

                    // Insert data album
                    Album a = new Album();
                    a.setIdAlbum(idAlbum);
                    a.setNamaAlbum(nama);
                    a.setGenre(genre);
                    a.setTahunRilis(tahun);

                    em.persist(a);
                    jumlahBerhasil++;
                }

                em.getTransaction().commit();
                showTableAlbum();

                JOptionPane.showMessageDialog(null,
                        "UPLOAD SELESAI!\n"
                        + "Berhasil: " + jumlahBerhasil + "\n"
                        + "Duplikat: " + jumlahDuplikat + "\n"
                        + "Data Error: " + jumlahGagal,
                        "Hasil Upload",
                        JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception ex) {
                if (em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat upload");
            } finally {
                em.close();
                emf.close();
            }
        }
    }//GEN-LAST:event_btnUploadAlbumActionPerformed

    private void btnCetakAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakAlbumActionPerformed
        JasperReport reports;

        String path = ".\\src\\DataMusik\\ReportAlbum.jasper";
        try {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
            }
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakAlbumActionPerformed

    private void btnCetakMusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakMusikActionPerformed
        JasperReport reports;

        String path = ".\\src\\DataMusik\\ReportMusik.jasper";
        try {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
            }
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakMusikActionPerformed

    private void btnUploadMusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadMusikActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File filePilihan = jfc.getSelectedFile();
            System.out.println("yang dipilih : " + filePilihan.getAbsolutePath());

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBOPertemuanDuabelasPU");
            EntityManager em = emf.createEntityManager();

            int jumlahBerhasil = 0;
            int jumlahDuplikat = 0;
            int jumlahAlbumTidakAda = 0;
            int jumlahKosong = 0;

            try (BufferedReader br = new BufferedReader(new FileReader(filePilihan))) {
                String baris;
                String pemisah = ";";

                em.getTransaction().begin();

                while ((baris = br.readLine()) != null) {
                    String[] data = baris.split(pemisah);

                    // Format: idMusik ; namaAlbum ; judul ; artis
                    if (data.length < 4) {
                        jumlahKosong++;
                        continue;
                    }

                    String idMusik = data[0].trim();
                    String namaAlbum = data[1].trim();
                    String judul = data[2].trim();
                    String artis = data[3].trim();

                    // Cek data kosong
                    if (idMusik.isEmpty() || namaAlbum.isEmpty()
                            || judul.isEmpty() || artis.isEmpty()) {
                        jumlahKosong++;
                        continue;
                    }

                    // Cek duplikat ID Musik
                    Musik cek = em.find(Musik.class, idMusik);
                    if (cek != null) {
                        jumlahDuplikat++;
                        continue;
                    }

                    // Cek album berdasarkan namaAlbum
                    Album album;
                    try {
                        Query qAlbum = em.createQuery("SELECT a FROM Album a WHERE a.namaAlbum = :nama");
                        qAlbum.setParameter("nama", namaAlbum);
                        album = (Album) qAlbum.getSingleResult();
                    } catch (NoResultException e) {
                        jumlahAlbumTidakAda++;
                        continue;
                    }

                    // Insert Musik
                    Musik m = new Musik();
                    m.setIdMusik(idMusik);
                    m.setJudul(judul);
                    m.setArtis(artis);
                    m.setIdAlbum(album);

                    em.persist(m);
                    jumlahBerhasil++;
                }

                em.getTransaction().commit();
                showTableMusik();

                JOptionPane.showMessageDialog(null,
                        "UPLOAD MUSIK SELESAI!\n"
                        + "Berhasil: " + jumlahBerhasil + "\n"
                        + "Duplikat ID Musik: " + jumlahDuplikat + "\n"
                        + "Album Tidak Ada: " + jumlahAlbumTidakAda + "\n"
                        + "Data Kosong/Tidak Lengkap: " + jumlahKosong,
                        "Hasil Upload Musik",
                        JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception ex) {
                if (em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat upload musik");
            } finally {
                em.close();
                emf.close();
            }
        }
    }//GEN-LAST:event_btnUploadMusikActionPerformed

    private void btnDownloadAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadAlbumActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan sebagai CSV");

        // Nama default
        fileChooser.setSelectedFile(new File("Data_Album.csv"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {

            File fileToSave = fileChooser.getSelectedFile();

            // Cek jika file sudah ada --> konfirmasi ke user
            if (fileToSave.exists()) {
                int confirm = JOptionPane.showConfirmDialog(
                        this,
                        "File sudah ada.\nApakah Anda ingin menimpanya?",
                        "Konfirmasi",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // batalkan
                }
            }

            try (FileWriter fw = new FileWriter(fileToSave)) {

                DefaultTableModel model = (DefaultTableModel) jTblAlbum.getModel();
                int colCount = model.getColumnCount();
                int rowCount = model.getRowCount();

                // Tulis isi tabel
                for (int r = 0; r < rowCount; r++) {
                    for (int c = 0; c < colCount; c++) {
                        Object value = model.getValueAt(r, c);
                        String cell = (value == null) ? "" : value.toString().replace(";", ",");
                        fw.write(cell);

                        if (c < colCount - 1) {
                            fw.write(";");
                        }
                    }
                    fw.write("\n");
                }

                JOptionPane.showMessageDialog(
                        this,
                        "Data album berhasil diekspor ke file CSV!\n" + fileToSave.getAbsolutePath(),
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE
                );

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Terjadi kesalahan saat menyimpan:\n" + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDownloadAlbumActionPerformed

    private void btnDownloadMusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadMusikActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan sebagai CSV");

        // Nama default
        fileChooser.setSelectedFile(new File("Data_Musik.csv"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {

            File fileToSave = fileChooser.getSelectedFile();

            // Cek jika file sudah ada
            if (fileToSave.exists()) {
                int confirm = JOptionPane.showConfirmDialog(
                        this,
                        "File sudah ada.\nApakah Anda ingin menimpanya?",
                        "Konfirmasi",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );
                if (confirm != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            try (FileWriter fw = new FileWriter(fileToSave)) {

                DefaultTableModel model = (DefaultTableModel) jTblMusik.getModel();
                int colCount = model.getColumnCount();
                int rowCount = model.getRowCount();

                // Tulis isi tabel
                for (int r = 0; r < rowCount; r++) {
                    for (int c = 0; c < colCount; c++) {
                        Object value = model.getValueAt(r, c);
                        String cell = (value == null) ? "" : value.toString().replace(";", ",");
                        fw.write(cell);
                        if (c < colCount - 1) {
                            fw.write(";");
                        }
                    }
                    fw.write("\n");
                }

                JOptionPane.showMessageDialog(
                        this,
                        "Data musik berhasil diekspor ke file CSV!\n" + fileToSave.getAbsolutePath(),
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE
                );

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Terjadi kesalahan saat menyimpan:\n" + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDownloadMusikActionPerformed

    private void btnResetAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetAlbumActionPerformed
        // TODO add your handling code here:
        EntityManager em = Persistence.createEntityManagerFactory("PBOPertemuanDuabelasPU").createEntityManager();

        try {
            em.getTransaction().begin();

            // Hapus semua data album (musik ikut kehapus karena cascade)
            em.createNativeQuery("TRUNCATE TABLE album CASCADE").executeUpdate();

            // Reset sequence musik (auto detect nama sequence)
            Object result = em.createNativeQuery("SELECT pg_get_serial_sequence('musik', 'id_musik')").getSingleResult();
            if (result != null) {
                String seqName = result.toString();
                em.createNativeQuery("ALTER SEQUENCE " + seqName + " RESTART WITH 1").executeUpdate();
            }

            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Data Album dan Musik berhasil direset!");

            showTableAlbum();
            showTableMusik();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal reset: " + e.getMessage());
        } finally {
            em.close();
        }
    }//GEN-LAST:event_btnResetAlbumActionPerformed

    private void btnResetMusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetMusikActionPerformed
        // TODO add your handling code here:
        EntityManager em = Persistence.createEntityManagerFactory("PBOPertemuanDuabelasPU").createEntityManager();

        try {
            em.getTransaction().begin();

            // Hapus semua data musik saja
            em.createNativeQuery("TRUNCATE TABLE musik").executeUpdate();

            // Cari sequence yang digunakan primary key musik
            Object result = em.createNativeQuery(
                    "SELECT pg_get_serial_sequence('musik', 'id_musik')")
                    .getSingleResult();

            // Jika sequence ditemukan → reset
            if (result != null) {
                String seqName = result.toString();
                em.createNativeQuery("ALTER SEQUENCE " + seqName + " RESTART WITH 1").executeUpdate();
            }

            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Data Musik berhasil direset!");

            showTableMusik();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal reset: " + e.getMessage());
        } finally {
            em.close();
        }
    }//GEN-LAST:event_btnResetMusikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakAlbum;
    private javax.swing.JButton btnCetakMusik;
    private javax.swing.JButton btnDeleteAlbum;
    private javax.swing.JButton btnDeleteMusik;
    private javax.swing.JButton btnDownloadAlbum;
    private javax.swing.JButton btnDownloadMusik;
    private javax.swing.JButton btnInsertAlbum;
    private javax.swing.JButton btnInsertMusik;
    private javax.swing.JButton btnResetAlbum;
    private javax.swing.JButton btnResetMusik;
    private javax.swing.JButton btnUpdateAlbum;
    private javax.swing.JButton btnUpdateMusik;
    private javax.swing.JButton btnUploadAlbum;
    private javax.swing.JButton btnUploadMusik;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTPAlbum;
    private javax.swing.JTable jTblAlbum;
    private javax.swing.JTable jTblMusik;
    private javax.swing.JLabel jlJudulForm;
    // End of variables declaration//GEN-END:variables
}
